name: Deploy on GH Pages

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  deploy:
    name: Publish site
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 6.0.2
    - run: pnpm install

    - run: pnpm docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vitepress/dist